/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '//(index)'
      | '//favorites'
      | '//help'
      | '//history'
      | '//performers'
      | '//playlists/(index)'
      | '//playlists/[playlistId]'
      | '//privacy'
      | '//requests/(index)'
      | '//requests/queue'
      | '//sites'
      | '//tags'
      | '//videos/(index)'
      | '//videos/[partnerVideoId]'
    >,
    '//(index)': RouteRecordInfo<
      '//(index)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//favorites': RouteRecordInfo<
      '//favorites',
      '/favorites',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//help': RouteRecordInfo<
      '//help',
      '/help',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//history': RouteRecordInfo<
      '//history',
      '/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//performers': RouteRecordInfo<
      '//performers',
      '/performers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//playlists/(index)': RouteRecordInfo<
      '//playlists/(index)',
      '/playlists',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//playlists/[playlistId]': RouteRecordInfo<
      '//playlists/[playlistId]',
      '/playlists/:playlistId',
      { playlistId: ParamValue<true> },
      { playlistId: ParamValue<false> },
      | never
    >,
    '//privacy': RouteRecordInfo<
      '//privacy',
      '/privacy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//requests/(index)': RouteRecordInfo<
      '//requests/(index)',
      '/requests',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//requests/queue': RouteRecordInfo<
      '//requests/queue',
      '/requests/queue',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//sites': RouteRecordInfo<
      '//sites',
      '/sites',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//tags': RouteRecordInfo<
      '//tags',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//videos/(index)': RouteRecordInfo<
      '//videos/(index)',
      '/videos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//videos/[partnerVideoId]': RouteRecordInfo<
      '//videos/[partnerVideoId]',
      '/videos/:partnerVideoId',
      { partnerVideoId: ParamValue<true> },
      { partnerVideoId: ParamValue<false> },
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
        | '//(index)'
        | '//favorites'
        | '//help'
        | '//history'
        | '//performers'
        | '//playlists/(index)'
        | '//playlists/[playlistId]'
        | '//privacy'
        | '//requests/(index)'
        | '//requests/queue'
        | '//sites'
        | '//tags'
        | '//videos/(index)'
        | '//videos/[partnerVideoId]'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/index/(index).vue': {
      routes:
        | '//(index)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/favorites.vue': {
      routes:
        | '//favorites'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/help.vue': {
      routes:
        | '//help'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/history.vue': {
      routes:
        | '//history'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/performers.vue': {
      routes:
        | '//performers'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/playlists/(index).vue': {
      routes:
        | '//playlists/(index)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/playlists/[playlistId].vue': {
      routes:
        | '//playlists/[playlistId]'
      views:
        | never
      pathParamNames:
        | 'playlistId'
    }
    'src/pages/index/privacy.vue': {
      routes:
        | '//privacy'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/requests/(index).vue': {
      routes:
        | '//requests/(index)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/requests/queue.vue': {
      routes:
        | '//requests/queue'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/sites.vue': {
      routes:
        | '//sites'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/tags.vue': {
      routes:
        | '//tags'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/videos/(index).vue': {
      routes:
        | '//videos/(index)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/videos/[partnerVideoId].vue': {
      routes:
        | '//videos/[partnerVideoId]'
      views:
        | never
      pathParamNames:
        | 'partnerVideoId'
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
